### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kobliha** [yast/autoyast-integration-test#54]
I have just a few comments for the README:

https://github.com/yast/autoyast-integration-test#running

The current workflow doesn't not work as it first describes how to run tests and then how to build an image. This can't work in that order. 
1. First of all, I'd maybe describe the workflow by saying something like: Tests are called on a pre-compiled ISO image, downloaded from $somewhere additionally using the newest packages added by DUD from $elsewhere. It's important to say, that the user needs to regenerate DUD/ISO(?) every time they want to test a new set of packages from $elsewhere / $somewhere. The mechanism is not clear.
2. Then I'd create another section "Test Environment Preparation" including `rake build_iso*`
3. Then I'd create another section "Running Test" including all `rake test*`
4. BTW, I'm somehow missing info for what the test actually tests - e.g., version of the ISO, date/time/something? This might be a bit hard.

Selecting a provider maybe belongs to "Running Test" (sub)section as user will try to run `rake` which will fail/run it in KVM instead of VirtualBox.

**Comment by kobliha** [comment]
BTW, I've checked what is in Jenkins:

    bundle install
    rake clobber
    rake build_iso[sles12-sp1]
    rake test[test/sles12.rb]
    rake test[test/tftp.rb]
    rake test[test/sles12_mini_network.rb]
    rake test[test/sles12_minimal.rb]
    rake test[test/sles12_minimal.rb]
    rake test[test/partition.rb]
    rake test[test/http.rb]

This sounds like a typical use-case / workflow. It would be quite nice to have that as an exemplary workflow :)

**Comment by imobach** [comment]
To be honest, that should be changed to `rake test`. We needed to do that because the 'upgrade scenario' was not working.

**Comment by schubi2** [comment]
And I must admit : LVM test is missing too :-)

**Comment by kobliha** [comment]
@imobach Everything covered? Can we close this issue?

**Comment by imobachgs** [comment]
These tests are not being used anymore, so I think it is time to close this issue. Thanks.
